/***********************************************************************
 * Copyright 1999-2015, ALTIBASE Corporation or its subsidiaries.
 * All rights reserved.
 **********************************************************************/

CREATE OR REPLACE PACKAGE DBMS_STANDARD AUTHID CURRENT_USER AS
FUNCTION INSERTING RETURN BOOLEAN;
FUNCTION UPDATING ( COLNAME IN VARCHAR(128) ) RETURN BOOLEAN;
FUNCTION UPDATING RETURN BOOLEAN;
FUNCTION DELETING RETURN BOOLEAN;
END DBMS_STANDARD;
/

CREATE PUBLIC SYNONYM DBMS_STANDARD FOR SYS.DBMS_STANDARD;
GRANT EXECUTE ON SYS.DBMS_STANDARD TO PUBLIC;
