/***********************************************************************
 * Copyright 1999-2015, ALTIBASE Corporation or its subsidiaries.
 * All rights reserved.
 **********************************************************************/

CREATE OR REPLACE PACKAGE BODY DBMS_STANDARD AS
FUNCTION INSERTING RETURN BOOLEAN AS
BEGIN
  RETURN _INSERTING();
END INSERTING;

FUNCTION UPDATING ( COLNAME IN VARCHAR(128) ) RETURN BOOLEAN AS
  UP_COLNAME VARCHAR(128);
BEGIN
  IF INSTR( COLNAME, CHR(34) ) = 0 THEN
    UP_COLNAME := UPPER( COLNAME );
ELSE
    UP_COLNAME := REPLACE2( COLNAME, CHR(34) );
END IF;

  RETURN _UPDATING(UP_COLNAME);
END UPDATING;

FUNCTION UPDATING RETURN BOOLEAN AS
BEGIN
  RETURN _UPDATING();
END UPDATING;

FUNCTION DELETING RETURN BOOLEAN AS
BEGIN
  RETURN _DELETING();
END DELETING;

END DBMS_STANDARD;
/
